/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as guestRouteRouteImport } from './routes/(guest)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as guestSignupRouteImport } from './routes/(guest)/signup'
import { Route as guestLoginRouteImport } from './routes/(guest)/login'
import { Route as authAppRouteRouteImport } from './routes/(auth)/app/route'
import { Route as authAppIndexRouteImport } from './routes/(auth)/app/index'
import { Route as authAppWebsocketRouteImport } from './routes/(auth)/app/websocket'
import { Route as authAppSseRouteImport } from './routes/(auth)/app/sse'

const guestRouteRoute = guestRouteRouteImport.update({
  id: '/(guest)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const guestSignupRoute = guestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => guestRouteRoute,
} as any)
const guestLoginRoute = guestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => guestRouteRoute,
} as any)
const authAppRouteRoute = authAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => authRouteRoute,
} as any)
const authAppIndexRoute = authAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authAppRouteRoute,
} as any)
const authAppWebsocketRoute = authAppWebsocketRouteImport.update({
  id: '/websocket',
  path: '/websocket',
  getParentRoute: () => authAppRouteRoute,
} as any)
const authAppSseRoute = authAppSseRouteImport.update({
  id: '/sse',
  path: '/sse',
  getParentRoute: () => authAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof authAppRouteRouteWithChildren
  '/login': typeof guestLoginRoute
  '/signup': typeof guestSignupRoute
  '/app/sse': typeof authAppSseRoute
  '/app/websocket': typeof authAppWebsocketRoute
  '/app/': typeof authAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof guestLoginRoute
  '/signup': typeof guestSignupRoute
  '/app/sse': typeof authAppSseRoute
  '/app/websocket': typeof authAppWebsocketRoute
  '/app': typeof authAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(guest)': typeof guestRouteRouteWithChildren
  '/(auth)/app': typeof authAppRouteRouteWithChildren
  '/(guest)/login': typeof guestLoginRoute
  '/(guest)/signup': typeof guestSignupRoute
  '/(auth)/app/sse': typeof authAppSseRoute
  '/(auth)/app/websocket': typeof authAppWebsocketRoute
  '/(auth)/app/': typeof authAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/sse'
    | '/app/websocket'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/app/sse' | '/app/websocket' | '/app'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(guest)'
    | '/(auth)/app'
    | '/(guest)/login'
    | '/(guest)/signup'
    | '/(auth)/app/sse'
    | '/(auth)/app/websocket'
    | '/(auth)/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  guestRouteRoute: typeof guestRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(guest)': {
      id: '/(guest)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)/signup': {
      id: '/(guest)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof guestSignupRouteImport
      parentRoute: typeof guestRouteRoute
    }
    '/(guest)/login': {
      id: '/(guest)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof guestLoginRouteImport
      parentRoute: typeof guestRouteRoute
    }
    '/(auth)/app': {
      id: '/(auth)/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof authAppRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/app/': {
      id: '/(auth)/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof authAppIndexRouteImport
      parentRoute: typeof authAppRouteRoute
    }
    '/(auth)/app/websocket': {
      id: '/(auth)/app/websocket'
      path: '/websocket'
      fullPath: '/app/websocket'
      preLoaderRoute: typeof authAppWebsocketRouteImport
      parentRoute: typeof authAppRouteRoute
    }
    '/(auth)/app/sse': {
      id: '/(auth)/app/sse'
      path: '/sse'
      fullPath: '/app/sse'
      preLoaderRoute: typeof authAppSseRouteImport
      parentRoute: typeof authAppRouteRoute
    }
  }
}

interface authAppRouteRouteChildren {
  authAppSseRoute: typeof authAppSseRoute
  authAppWebsocketRoute: typeof authAppWebsocketRoute
  authAppIndexRoute: typeof authAppIndexRoute
}

const authAppRouteRouteChildren: authAppRouteRouteChildren = {
  authAppSseRoute: authAppSseRoute,
  authAppWebsocketRoute: authAppWebsocketRoute,
  authAppIndexRoute: authAppIndexRoute,
}

const authAppRouteRouteWithChildren = authAppRouteRoute._addFileChildren(
  authAppRouteRouteChildren,
)

interface authRouteRouteChildren {
  authAppRouteRoute: typeof authAppRouteRouteWithChildren
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAppRouteRoute: authAppRouteRouteWithChildren,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface guestRouteRouteChildren {
  guestLoginRoute: typeof guestLoginRoute
  guestSignupRoute: typeof guestSignupRoute
}

const guestRouteRouteChildren: guestRouteRouteChildren = {
  guestLoginRoute: guestLoginRoute,
  guestSignupRoute: guestSignupRoute,
}

const guestRouteRouteWithChildren = guestRouteRoute._addFileChildren(
  guestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  guestRouteRoute: guestRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
